#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
from traceback import print_exc

from schranz.client import execute_command

def main(argv):
    argv = argv[1:]
    if len(argv) < 2:
        print 'At least two arguments are needed: module name and command'
        return 1
    (module, command), arguments = argv[:2], argv[2:]
    try:
        result = execute_command(module, command, arguments)
        errors = result.get('errors')
        if errors:
            print 'Errors occured:'
            print '\n'.join(errors)
            return 1
    except:
        print_exc()
        return 1
    return 0

if __name__ == '__main__':
    argv = list(sys.argv)
    code = main(argv)
    sys.exit(code or 0)
