#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import signal
import sys
from traceback import print_exc

from schranz.util import get_group, get_user
from schranz.daemon import SchranzDaemon

def main(argv):
    try:
        pid = os.fork()
        if pid:
            sys.exit(0)
    except Exception, e:
        print >>sys.stderr, 'Could not daemonize'
        return 1

    f = open('/var/run/schranz/schranz.pid', 'w')
    f.write(str(os.getpid()))
    f.close()
    
    try:
        os.setgid(get_group(name = 'schranz').gr_gid)
    except:
        print >>sys.stderr, 'Cannot change group. Daemon will run as group %s.' % get_group(gid = os.getgid()).gr_name

    try:
        os.setuid(get_user(name = 'schranz').pw_uid)
    except:
        print >>sys.stderr, 'Cannot change user. Daemon will run as user %s.' % get_user(uid = os.getuid()).pw_name

    daemon = SchranzDaemon()
    
    def handler(i, j):
        daemon.stop()

    signal.signal(signal.SIGQUIT, handler)
    signal.signal(signal.SIGTERM, handler)

    try:
        daemon.run()
    except KeyboardInterrupt:
        daemon.stop()
    except:
        print_exc()
        return 1

    return 0

if __name__ == '__main__':
    argv = list(sys.argv)
    code = main(argv)
    sys.exit(code or 0)

