#!/usr/bin/env python
# -*- coding: utf-8 -*-

import signal
import sys
from traceback import print_exc

from schranz.daemon import SchranzDaemon

def main(argv):
    daemon = SchranzDaemon()
    
    def handler(i, j):
        daemon.stop()

    signal.signal(signal.SIGQUIT, handler)
    signal.signal(signal.SIGTERM, handler)

    try:
        daemon.run()
    except KeyboardInterrupt:
        daemon.stop()
    except:
        print_exc()
        return 1

    return 0

if __name__ == '__main__':
    argv = list(sys.argv)
    code = main(argv)
    sys.exit(code or 0)

